server:
  port: 8090

# Lowcode 相关配置
lowcode:
  security:
    # 前端传输密码的 AES 加密密钥
    password-secret-key: '==LowCode-Auth=='
    oauth2:
      authorizationserver:
        # 登陆验证码是否开启
        login-captcha-enabled: true
      resourceserver:
        ## 是否与资源服务器，共享token存储环境
        shared-stored-token: true
        ## 忽略鉴权的 url 列表
        ignore-urls:
          - /public/**
          - /actuator/**
          - /doc.html
          - /v2/api-docs/**
          - /v3/api-docs/**
          - /swagger-resources/**
          - /swagger-ui/**
          - /webjars/**
          - /bycdao-ui/**
          - /favicon.ico
          - /captcha/**
  # 项目 redis 缓存的 key 前缀
  redis:
    key-prefix: 'lowcode:'
  # actuator 加解密密钥
  actuator:
    auth: true
    secret-id: 'cias-monitor'
    secret-key: '=cias-Monitor'
  openapi:
    info:
      title: LowCode-Admin Docs
      description: LowCode 后台管理服务Api文档
      version: ${project.version}
      terms-of-service: http://www.lowcode.cn/
      license:
        name: Powered By LowCode
        url: http://www.lowcode.cn/
      contact:
        name: pengxinxin
        email: pengxinxin@cias.cn
        url: http://www.cias.cn/
    components:
      security-schemes:
        apiKey:
          type: APIKEY
          in: HEADER
          name: 'api-key'
        oauth2:
          type: OAUTH2
          flows:
            password:
              token-url: /oauth/token
    security:
      - oauth2: []
      - apiKey: []