server:
  port: 18084

dubbo:
  application:
    name: dubbo-provider
  protocol:
    port: 28084
    name: dubbo

  scan:
    base-packages: com.tupelo.dubbo.provider.service.impl
  registry:
    address: zookeeper://106.52.145.64:2181?timeout=30000
  provider:
    weight: 3
    loadbalance: roundrobin
